/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PIN_MUX_H_
#define _PIN_MUX_H_

/*!
 * @addtogroup pin_mux
 * @{
 */

/***********************************************************************************************************************
 * API
 **********************************************************************************************************************/

#if defined(__cplusplus)
extern "C" {
#endif

/*!
 * @brief Calls initialization functions.
 *
 */
void BOARD_InitBootPins(void);

/*!
 * @brief UART 1 receive data source select: UART1_RX pin */
#define SOPT5_UART1RXSRC_UART_RX 0x00u
/*!
 * @brief UART 1 transmit data source select: UART1_TX pin */
#define SOPT5_UART1TXSRC_UART_TX 0x00u
/*!
 * @brief FTM3 channel 0 output source: FTM3_CH0 pin is output of FTM3 channel 0 output */
#define SOPT8_FTM3OCH0SRC_FTM 0x00u
/*!
 * @brief FTM3 channel 1 output source: FTM3_CH1 pin is output of FTM3 channel 1 output */
#define SOPT8_FTM3OCH1SRC_FTM 0x00u
/*!
 * @brief FTM3 channel 2 output source: FTM3_CH2 pin is output of FTM3 channel 2 output */
#define SOPT8_FTM3OCH2SRC_FTM 0x00u
/*!
 * @brief FTM3 channel 3 output source: FTM3_CH3 pin is output of FTM3 channel 3 output */
#define SOPT8_FTM3OCH3SRC_FTM 0x00u
/*!
 * @brief FTM3 channel 4 output source: FTM3_CH4 pin is output of FTM3 channel 4 output */
#define SOPT8_FTM3OCH4SRC_FTM 0x00u
/*!
 * @brief FTM3 channel 5 output source: FTM3_CH5 pin is output of FTM3 channel 5 output */
#define SOPT8_FTM3OCH5SRC_FTM 0x00u

/*! @name PORTA16 (number 46), Light
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_Light_GPIO GPIOA                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_Light_GPIO_PIN_MASK (1U << 16U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_Light_PORT PORTA                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_Light_PIN 16U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_Light_PIN_MASK (1U << 16U)      /*!<@brief PORT pin mask */
                                                       /* @} */

/*! @name PORTD2 (number 95), PWMB
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_PWMB_PORT PORTD               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_PWMB_PIN 2U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_PWMB_PIN_MASK (1U << 2U)      /*!<@brief PORT pin mask */
                                                     /* @} */

/*! @name PORTD3 (number 96), PWMB_N
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_PWMB_N_PORT PORTD               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_PWMB_N_PIN 3U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_PWMB_N_PIN_MASK (1U << 3U)      /*!<@brief PORT pin mask */
                                                       /* @} */

/*! @name PORTE5 (number 6), PWMA
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_PWMA_PORT PORTE               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_PWMA_PIN 5U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_PWMA_PIN_MASK (1U << 5U)      /*!<@brief PORT pin mask */
                                                     /* @} */

/*! @name PORTE6 (number 7), PWMA_N
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_PWMA_N_PORT PORTE               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_PWMA_N_PIN 6U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_PWMA_N_PIN_MASK (1U << 6U)      /*!<@brief PORT pin mask */
                                                       /* @} */

/*! @name PORTC8 (number 80), PWMC
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_PWMC_PORT PORTC               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_PWMC_PIN 8U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_PWMC_PIN_MASK (1U << 8U)      /*!<@brief PORT pin mask */
                                                     /* @} */

/*! @name PORTC9 (number 81), PWMC_N
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_PWMC_N_PORT PORTC               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_PWMC_N_PIN 9U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_PWMC_N_PIN_MASK (1U << 9U)      /*!<@brief PORT pin mask */
                                                       /* @} */

/*! @name PORTA13 (number 43), pwm_src
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_pwm_src_GPIO GPIOA                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_pwm_src_GPIO_PIN_MASK (1U << 13U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_pwm_src_PORT PORTA                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_pwm_src_PIN 13U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_pwm_src_PIN_MASK (1U << 13U)      /*!<@brief PORT pin mask */
                                                         /* @} */

/*! @name PORTE1 (number 2), theta_code_RX
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_theta_code_RX_PORT PORTE               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_theta_code_RX_PIN 1U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_theta_code_RX_PIN_MASK (1U << 1U)      /*!<@brief PORT pin mask */
                                                              /* @} */

/*! @name PORTE0 (number 1), theta_code_TX
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_theta_code_TX_PORT PORTE               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_theta_code_TX_PIN 0U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_theta_code_TX_PIN_MASK (1U << 0U)      /*!<@brief PORT pin mask */
                                                              /* @} */

/*! @name PORTE3 (number 4), CODE_ORDER
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_CODE_ORDER_GPIO GPIOE               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_CODE_ORDER_GPIO_PIN_MASK (1U << 3U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_CODE_ORDER_PORT PORTE               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_CODE_ORDER_PIN 3U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_CODE_ORDER_PIN_MASK (1U << 3U)      /*!<@brief PORT pin mask */
                                                           /* @} */

/*! @name PORTE4 (number 5), u_get
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_Udc_PORT PORTE               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_Udc_PIN 4U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_Udc_PIN_MASK (1U << 4U)      /*!<@brief PORT pin mask */
                                                    /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitPins(void);

#if defined(__cplusplus)
}
#endif

/*!
 * @}
 */
#endif /* _PIN_MUX_H_ */

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
