/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
!!GlobalInfo
product: Pins v12.0
processor: MKV56F512xxx24
package_id: MKV56F512VLL24
mcu_data: ksdk2_0
processor_version: 12.0.0
pin_labels:
- {pin_num: '46', pin_signal: CMP3_IN2/PTA16/SPI0_SOUT/UART0_CTS_b/UART0_COL_b, label: Light, identifier: Light}
- {pin_num: '95', pin_signal: PTD2/LLWU_P13/SPI0_SOUT/UART2_RX/FTM3_CH2/FTM0_CH2/FLEXPWM0_A1/I2C0_SCL/FB_AD4/FLEXPWM1_A1, label: PWMB, identifier: PWM;PWMB}
- {pin_num: '96', pin_signal: PTD3/SPI0_SIN/UART2_TX/FTM3_CH3/FTM0_CH3/FLEXPWM0_B1/I2C0_SDA/FB_AD3/FLEXPWM1_B1, label: PWMB_N, identifier: PWM_N;PWMB_N}
- {pin_num: '6', pin_signal: HSADC1A_CH5/ADC0_SE10/ADC0_DM2/PTE5/SPI1_PCS2/UART3_RX/FLEXPWM1_A0/FTM3_CH0, label: PWMA, identifier: PWMA}
- {pin_num: '7', pin_signal: HSADC1B_CH7/ADC0_SE4a/PTE6/LLWU_P16/SPI1_PCS3/UART3_CTS_b/FLEXPWM1_B0/FTM3_CH1, label: PWMA_N, identifier: PWMA_N}
- {pin_num: '80', pin_signal: HSADC1B_CH11/CMP0_IN2/PTC8/FTM3_CH4/FLEXPWM1_A2/FB_AD7, label: PWMC, identifier: PWMC}
- {pin_num: '81', pin_signal: HSADC1B_CH12/CMP0_IN3/PTC9/FTM3_CH5/FLEXPWM1_B2/FB_AD6, label: PWMC_N, identifier: PWMC_N}
- {pin_num: '1', pin_signal: HSADC0B_CH16/HSADC1A_CH0/PTE0/SPI1_PCS1/UART1_TX/XB_OUT10/XB_IN11/I2C1_SDA/TRACE_CLKOUT, label: theta_code_TX, identifier: Uart1_TX;theta_code_TX}
- {pin_num: '2', pin_signal: HSADC0B_CH17/HSADC1A_CH1/PTE1/LLWU_P0/SPI1_SOUT/UART1_RX/XB_OUT11/XB_IN7/I2C1_SCL/TRACE_D3, label: theta_code_RX, identifier: Uart1_RX;theta_code_RX}
- {pin_num: '5', pin_signal: HSADC1A_CH4/ADC0_SE2/ADC0_DP2/PTE4/LLWU_P2/SPI1_PCS0/UART3_TX/TRACE_D0, label: u_get, identifier: Udc;Uref;uref}
- {pin_num: '43', pin_signal: CMP2_IN1/PTA13/LLWU_P4/CAN0_RX/FTM1_CH1/FTM1_QD_PHB/I2C1_SDA, label: pwm_src, identifier: pwm_src}
- {pin_num: '4', pin_signal: HSADC0B_CH11/HSADC1B_CH1/PTE3/SPI1_SIN/UART1_RTS_b/TRACE_D1, label: CODE_ORDER, identifier: CODE_ORDER}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

#include "fsl_common.h"
#include "fsl_port.h"
#include "fsl_gpio.h"
#include "pin_mux.h"

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitBootPins
 * Description   : Calls initialization functions.
 *
 * END ****************************************************************************************************************/
void BOARD_InitBootPins(void)
{
    BOARD_InitPins();
}

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_InitPins:
- options: {callFromInitBoot: 'true', coreID: core0, enableClock: 'true'}
- pin_list:
  - {pin_num: '46', peripheral: GPIOA, signal: 'GPIO, 16', pin_signal: CMP3_IN2/PTA16/SPI0_SOUT/UART0_CTS_b/UART0_COL_b, direction: OUTPUT}
  - {pin_num: '95', peripheral: FTM3, signal: 'CH, 2', pin_signal: PTD2/LLWU_P13/SPI0_SOUT/UART2_RX/FTM3_CH2/FTM0_CH2/FLEXPWM0_A1/I2C0_SCL/FB_AD4/FLEXPWM1_A1, identifier: PWMB,
    direction: OUTPUT, drive_strength: low}
  - {pin_num: '96', peripheral: FTM3, signal: 'CH, 3', pin_signal: PTD3/SPI0_SIN/UART2_TX/FTM3_CH3/FTM0_CH3/FLEXPWM0_B1/I2C0_SDA/FB_AD3/FLEXPWM1_B1, identifier: PWMB_N,
    direction: OUTPUT, drive_strength: low}
  - {pin_num: '6', peripheral: FTM3, signal: 'CH, 0', pin_signal: HSADC1A_CH5/ADC0_SE10/ADC0_DM2/PTE5/SPI1_PCS2/UART3_RX/FLEXPWM1_A0/FTM3_CH0, direction: OUTPUT,
    drive_strength: low}
  - {pin_num: '7', peripheral: FTM3, signal: 'CH, 1', pin_signal: HSADC1B_CH7/ADC0_SE4a/PTE6/LLWU_P16/SPI1_PCS3/UART3_CTS_b/FLEXPWM1_B0/FTM3_CH1, direction: OUTPUT}
  - {pin_num: '80', peripheral: FTM3, signal: 'CH, 4', pin_signal: HSADC1B_CH11/CMP0_IN2/PTC8/FTM3_CH4/FLEXPWM1_A2/FB_AD7, direction: OUTPUT}
  - {pin_num: '81', peripheral: FTM3, signal: 'CH, 5', pin_signal: HSADC1B_CH12/CMP0_IN3/PTC9/FTM3_CH5/FLEXPWM1_B2/FB_AD6, direction: OUTPUT}
  - {pin_num: '43', peripheral: GPIOA, signal: 'GPIO, 13', pin_signal: CMP2_IN1/PTA13/LLWU_P4/CAN0_RX/FTM1_CH1/FTM1_QD_PHB/I2C1_SDA, direction: OUTPUT}
  - {pin_num: '2', peripheral: UART1, signal: RX, pin_signal: HSADC0B_CH17/HSADC1A_CH1/PTE1/LLWU_P0/SPI1_SOUT/UART1_RX/XB_OUT11/XB_IN7/I2C1_SCL/TRACE_D3, identifier: theta_code_RX}
  - {pin_num: '1', peripheral: UART1, signal: TX, pin_signal: HSADC0B_CH16/HSADC1A_CH0/PTE0/SPI1_PCS1/UART1_TX/XB_OUT10/XB_IN11/I2C1_SDA/TRACE_CLKOUT, identifier: theta_code_TX,
    direction: OUTPUT}
  - {pin_num: '4', peripheral: GPIOE, signal: 'GPIO, 3', pin_signal: HSADC0B_CH11/HSADC1B_CH1/PTE3/SPI1_SIN/UART1_RTS_b/TRACE_D1, direction: OUTPUT, gpio_init_state: 'true'}
  - {pin_num: '5', peripheral: ADC0, signal: 'SE, 2', pin_signal: HSADC1A_CH4/ADC0_SE2/ADC0_DP2/PTE4/LLWU_P2/SPI1_PCS0/UART3_TX/TRACE_D0, identifier: Udc}
  - {pin_num: '12', peripheral: ADC0, signal: 'SE, 5a', pin_signal: HSADC0B_CH0/ADC0_SE5a/PTE18/LLWU_P20/SPI0_SOUT/UART2_CTS_b/I2C0_SDA}
  - {pin_num: '13', peripheral: ADC0, signal: 'SE, 6a', pin_signal: HSADC0B_CH1/ADC0_SE6a/PTE19/SPI0_SIN/UART2_RTS_b/I2C0_SCL/CMP3_OUT}
  - {pin_num: '16', peripheral: ADC0, signal: 'SE, 5b', pin_signal: HSADC0A_CH8/ADC0_SE5b/PTE20/FTM1_CH0/UART0_TX/FTM1_QD_PHA}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitPins
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void BOARD_InitPins(void)
{
    /* Port A Clock Gate Control: Clock enabled */
    CLOCK_EnableClock(kCLOCK_PortA);
    /* Port C Clock Gate Control: Clock enabled */
    CLOCK_EnableClock(kCLOCK_PortC);
    /* Port D Clock Gate Control: Clock enabled */
    CLOCK_EnableClock(kCLOCK_PortD);
    /* Port E Clock Gate Control: Clock enabled */
    CLOCK_EnableClock(kCLOCK_PortE);

    gpio_pin_config_t pwm_src_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTA13 (pin 43)  */
    GPIO_PinInit(BOARD_INITPINS_pwm_src_GPIO, BOARD_INITPINS_pwm_src_PIN, &pwm_src_config);

    gpio_pin_config_t Light_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTA16 (pin 46)  */
    GPIO_PinInit(BOARD_INITPINS_Light_GPIO, BOARD_INITPINS_Light_PIN, &Light_config);

    gpio_pin_config_t CODE_ORDER_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 1U
    };
    /* Initialize GPIO functionality on pin PTE3 (pin 4)  */
    GPIO_PinInit(BOARD_INITPINS_CODE_ORDER_GPIO, BOARD_INITPINS_CODE_ORDER_PIN, &CODE_ORDER_config);

    /* PORTA13 (pin 43) is configured as PTA13 */
    PORT_SetPinMux(BOARD_INITPINS_pwm_src_PORT, BOARD_INITPINS_pwm_src_PIN, kPORT_MuxAsGpio);

    /* PORTA16 (pin 46) is configured as PTA16 */
    PORT_SetPinMux(BOARD_INITPINS_Light_PORT, BOARD_INITPINS_Light_PIN, kPORT_MuxAsGpio);

    /* PORTC8 (pin 80) is configured as FTM3_CH4 */
    PORT_SetPinMux(BOARD_INITPINS_PWMC_PORT, BOARD_INITPINS_PWMC_PIN, kPORT_MuxAlt3);

    /* PORTC9 (pin 81) is configured as FTM3_CH5 */
    PORT_SetPinMux(BOARD_INITPINS_PWMC_N_PORT, BOARD_INITPINS_PWMC_N_PIN, kPORT_MuxAlt3);

    /* PORTD2 (pin 95) is configured as FTM3_CH2 */
    PORT_SetPinMux(BOARD_INITPINS_PWMB_PORT, BOARD_INITPINS_PWMB_PIN, kPORT_MuxAlt4);

    /* PORTD3 (pin 96) is configured as FTM3_CH3 */
    PORT_SetPinMux(BOARD_INITPINS_PWMB_N_PORT, BOARD_INITPINS_PWMB_N_PIN, kPORT_MuxAlt4);

    /* PORTE0 (pin 1) is configured as UART1_TX */
    PORT_SetPinMux(BOARD_INITPINS_theta_code_TX_PORT, BOARD_INITPINS_theta_code_TX_PIN, kPORT_MuxAlt3);

    /* PORTE1 (pin 2) is configured as UART1_RX */
    PORT_SetPinMux(BOARD_INITPINS_theta_code_RX_PORT, BOARD_INITPINS_theta_code_RX_PIN, kPORT_MuxAlt3);

    /* PORTE18 (pin 12) is configured as ADC0_SE5a */
    PORT_SetPinMux(PORTE, 18U, kPORT_PinDisabledOrAnalog);

    /* PORTE19 (pin 13) is configured as ADC0_SE6a */
    PORT_SetPinMux(PORTE, 19U, kPORT_PinDisabledOrAnalog);

    /* PORTE20 (pin 16) is configured as ADC0_SE5b */
    PORT_SetPinMux(PORTE, 20U, kPORT_PinDisabledOrAnalog);

    /* PORTE3 (pin 4) is configured as PTE3 */
    PORT_SetPinMux(BOARD_INITPINS_CODE_ORDER_PORT, BOARD_INITPINS_CODE_ORDER_PIN, kPORT_MuxAsGpio);

    /* PORTE4 (pin 5) is configured as ADC0_SE2 */
    PORT_SetPinMux(BOARD_INITPINS_Udc_PORT, BOARD_INITPINS_Udc_PIN, kPORT_PinDisabledOrAnalog);

    /* PORTE5 (pin 6) is configured as FTM3_CH0 */
    PORT_SetPinMux(BOARD_INITPINS_PWMA_PORT, BOARD_INITPINS_PWMA_PIN, kPORT_MuxAlt6);

    PORTE->PCR[5] = ((PORTE->PCR[5] &
                      /* Mask bits to zero which are setting */
                      (~(PORT_PCR_DSE_MASK | PORT_PCR_ISF_MASK)))

                     /* Drive Strength Enable: Low drive strength is configured on the corresponding pin, if pin
                      * is configured as a digital output. */
                     | PORT_PCR_DSE(kPORT_LowDriveStrength));

    /* PORTE6 (pin 7) is configured as FTM3_CH1 */
    PORT_SetPinMux(BOARD_INITPINS_PWMA_N_PORT, BOARD_INITPINS_PWMA_N_PIN, kPORT_MuxAlt6);

    SIM->SOPT5 = ((SIM->SOPT5 &
                   /* Mask bits to zero which are setting */
                   (~(SIM_SOPT5_UART1TXSRC_MASK | SIM_SOPT5_UART1RXSRC_MASK)))

                  /* UART 1 transmit data source select: UART1_TX pin. */
                  | SIM_SOPT5_UART1TXSRC(SOPT5_UART1TXSRC_UART_TX)

                  /* UART 1 receive data source select: UART1_RX pin. */
                  | SIM_SOPT5_UART1RXSRC(SOPT5_UART1RXSRC_UART_RX));

    SIM->SOPT8 =
        ((SIM->SOPT8 &
          /* Mask bits to zero which are setting */
          (~(SIM_SOPT8_FTM3OCH0SRC_MASK | SIM_SOPT8_FTM3OCH1SRC_MASK | SIM_SOPT8_FTM3OCH2SRC_MASK | SIM_SOPT8_FTM3OCH3SRC_MASK | SIM_SOPT8_FTM3OCH4SRC_MASK | SIM_SOPT8_FTM3OCH5SRC_MASK)))

         /* FTM3 channel 0 output source: FTM3_CH0 pin is output of FTM3 channel 0 output. */
         | SIM_SOPT8_FTM3OCH0SRC(SOPT8_FTM3OCH0SRC_FTM)

         /* FTM3 channel 1 output source: FTM3_CH1 pin is output of FTM3 channel 1 output. */
         | SIM_SOPT8_FTM3OCH1SRC(SOPT8_FTM3OCH1SRC_FTM)

         /* FTM3 channel 2 output source: FTM3_CH2 pin is output of FTM3 channel 2 output. */
         | SIM_SOPT8_FTM3OCH2SRC(SOPT8_FTM3OCH2SRC_FTM)

         /* FTM3 channel 3 output source: FTM3_CH3 pin is output of FTM3 channel 3 output. */
         | SIM_SOPT8_FTM3OCH3SRC(SOPT8_FTM3OCH3SRC_FTM)

         /* FTM3 channel 4 output source: FTM3_CH4 pin is output of FTM3 channel 4 output. */
         | SIM_SOPT8_FTM3OCH4SRC(SOPT8_FTM3OCH4SRC_FTM)

         /* FTM3 channel 5 output source: FTM3_CH5 pin is output of FTM3 channel 5 output. */
         | SIM_SOPT8_FTM3OCH5SRC(SOPT8_FTM3OCH5SRC_FTM));
}
/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
